apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-trigger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: github-actions-trigger
    spec:
      containers:
      - name: github-actions-trigger
        imagePullPolicy: Always
        image: pyama/github-actions-trigger:latest
        tty: true
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        env:
          - name: REDIS_URL
            value: "redis-service:6379"
          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                name: github-actions-trigger
                key: slack-signing-token
          - name: TZ
            value: Asia/Tokyo
          - name: SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-actions-trigger
                key: slack-bot-token
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-actions-trigger
                key: github-token
