apiVersion: v1
kind: Service
metadata:
  name: github-actions-trigger
spec:
  type: LoadBalancer
  selector:
    name: github-actions-trigger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: github-actions-trigger
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
